import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import StreamMonitor from "../components/StreamMonitor/StreamMonitor";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StreamMonitor></StreamMonitor>
    </>
  );
};

export default Home;
